language: node_js
node_js:
  - '8'
services:
  - docker
env:
  global: PR_ONLY=true
stages:
  - block merges to private repo
  - test
jobs:
  include:
    - stage: block merges to private repo
      install: skip
      script: exit 1
      if: (type = pull_request) AND (branch = master) AND (repo = Azure/azure-rest-api-specs-pr)
    - stage: test
      script: npm test -- test/syntax.js
      env: NAME=SyntaxValidation
    - script: npm test -- test/semantic.js
      env: NAME=SemanticValidation
    - script: npm test -- test/model.js
      env: NAME=ModelValidation
    - script: node -- scripts/breaking-change.js
      env: NAME=BreakingChanges
    - script: node -- scripts/liveValidation.js
      env: NAME=LiveValidation
    - script: scripts/install-dotnet.sh && npm test -- test/linter.js
      env: NAME=Linter
    - script: scripts/install-dotnet.sh && node -- scripts/momentOfTruth.js && node -- scripts/momentOfTruthPostProcessing.js
      env: NAME=NewLintIssues
    - script: travis_wait 30 scripts/swagger-to-sdk.sh Azure/azure-sdk-for-python -v
      env: NAME=BuildPython
    - script: travis_wait 30 scripts/swagger-to-sdk.sh Azure/azure-sdk-for-node -v
      env: NAME=BuildNode
    - script: travis_wait 30 scripts/swagger-to-sdk.sh Azure/azure-sdk-for-ruby -v
      env: NAME=BuildRuby
    - script: travis_wait 30 scripts/swagger-to-sdk.sh Azure/azure-sdk-for-go -o latest -v
      env: NAME=BuildGo
    - script: travis_wait 30 scripts/swagger-to-sdk.sh Azure/azure-libraries-for-java -v
      env: NAME=BuildJava
  allow_failures:
    - env: NAME=ModelValidation
    - env: NAME=BreakingChanges
    - env: NAME=LiveValidation
    - env: NAME=Linter
    - env: NAME=NewLintIssues
    - env: NAME=BuildNode
    - env: NAME=BuildRuby
    - env: NAME=BuildGo
    - env: NAME=BuildJava
  fast_finish: true